# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Christian Monaghan
baseurl:        ""
url:            "https://www.christianmonaghan.com"

# Collections
collections:
  writing:
    output: true
    permalink: /writing/:path/
  speaking:
    output: true
    permalink: /speaking/:path/

# number of teaser posts to show on the landing page
teaser_count:   3

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Christian Monaghan
  url:          https://www.christianmonaghan.com
  # email:        test@test.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/cmonaghan/cmonaghan.github.io

# Plugins / Gems
plugins:
  - jekyll-paginate-v2

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many paginated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

############################################################
# Site configuration for the Auto-Pages feature
autopages:

  # Site-wide kill switch, disable here and it doesn't run at all
  enabled: true

  # Collection pages, omit to disable
  collections:
    layouts:
      - 'post-catalogue.html'
    title: ':coll' # :coll is replaced by the collection name
    permalink: '/:coll'
    enabled: true
